
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SqlProject
{

using System;
    using System.Collections.Generic;
    
public partial class exam
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public exam()
    {

        this.Students_exams_questions = new HashSet<Students_exams_questions>();

        this.student_exam = new HashSet<student_exam>();

    }


    public int exam_ID { get; set; }

    public int course_ID { get; set; }

    public Nullable<int> duration { get; set; }

    public Nullable<int> exam_total_degree { get; set; }



    public virtual cours cours { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Students_exams_questions> Students_exams_questions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<student_exam> student_exam { get; set; }

}

}
