
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SqlProject
{

using System;
    using System.Collections.Generic;
    
public partial class student_exam
{

    public int student_ID { get; set; }

    public int exam_ID { get; set; }

    public Nullable<int> exam_grade { get; set; }



    public virtual exam exam { get; set; }

    public virtual student student { get; set; }

}

}
