
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SqlProject
{

using System;
    using System.Collections.Generic;
    
public partial class student
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public student()
    {

        this.student_exam = new HashSet<student_exam>();

        this.Students_exams_questions = new HashSet<Students_exams_questions>();

        this.courses = new HashSet<cours>();

    }


    public int student_ID { get; set; }

    public string student_Fname { get; set; }

    public string student_Lname { get; set; }

    public int department_ID { get; set; }

    public string student_UserName { get; set; }

    public string student_Password { get; set; }



    public virtual department department { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<student_exam> student_exam { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Students_exams_questions> Students_exams_questions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<cours> courses { get; set; }

}

}
